DATA: 
  PATH: "/home/dinggd/datasets"
  DATASET: "50salads"
  SAMPLE_RATE: 2
  FEATURE_DIM: 2048
  SPLIT: 1

MODEL:
  NAME: 'asformer'

ASFORMER:
  NUM_STAGES: 4
  NUM_LAYERS: 10
  NUM_F_MAPS: 64
  NUM_DECODERS: 4
  CHANNEL_MASK_RATE: 0.3
  R1: 2
  R2: 2

TRAIN:
  BZ: 1
  LR: 0.0001
  NUM_EPOCHS: 30
