DATA: 
  PATH: "/home/dinggd/datasets"
  DATASET: "50salads"
  SAMPLE_RATE: 8
  TEMPORAL_AUG: True
  FEATURE_DIM: 2048
  SPLIT: 1

MODEL:
  NAME: 'diffact'

DIFFACT:
  ENCODER_PARAMS:
    USE_INSTANCE_NORM: False
    NUM_LAYERS: 10
    NUM_F_MAPS: 64
    KERNEL_SIZE: 5
    NORMAL_DROPOUT_RATE: 0.5
    CHANNEL_DROPOUT_RATE: 0.5
    TEMPORAL_DROPOUT_RATE: 0.5
    FEATURE_LAYER_INDICES:
    - 5
    - 7
    - 9

  DECODER_PARAMS:
    NUM_LAYERS: 8
    NUM_F_MAPS: 24
    TIME_EMB_DIM: 512
    KERNEL_SIZE: 7
    DROPOUT_RATE: 0.1

  DIFFUSION_PARAMS:
    TIMESTEPS: 1000
    SAMPLING_TIMESTEPS: 25
    DDIM_SAMPLING_ETA: 1.0
    SNR_SCALE: 1.0
    COND_TYPES:
    - "full"
    - "zero"
    - "boundary05-"
    - "segment=2"
    - "segment=2"
    DETACH_DECODER: False

  POSTPROCESS:
    TYPE: "median"
    VALUE: 30


LOSS_WEIGHTS:
  ENCODER_CE_LOSS: 0.5
  ENCODER_MSE_LOSS: 0.1
  ENCODER_BOUNDARY_LOSS: 0.0
  DECODER_CE_LOSS: 0.5
  DECODER_MSE_LOSS: 0.1
  DECODER_BOUNDARY_LOSS: 0.1

TRAIN:
  BZ: 4
  LR: 0.0005
  WEIGHT_DECAY: 0.0
  NUM_EPOCHS: 5001
  LOG_FREQ: 100
  CLASS_WEIGHTING: True
  SET_SAMPLING_SEED: True
  BOUNDARY_SMOOTH: 20
  SOFT_LABEL: None
  LOG_TRAIN_RESULTS: False
