DATA: 
  PATH: "/home/dinggd/datasets"
  DATASET: "50salads"
  SAMPLE_RATE: 2
  FEATURE_DIM: 2048
  SPLIT: 1

MODEL:
  NAME: 'mstcn'

MSTCN:
  NUM_STAGES: 4
  NUM_LAYERS: 10
  NUM_F_MAPS: 64

TRAIN:
  BZ: 8
  LR: 0.0005
  NUM_EPOCHS: 50
