DATA:
  PATH: "dataset"
  DATASET: "breakfast"
  FEATURE_DIM: 2048
  SPLIT: 1
  CHUNK_SIZE: 10
  MAX_FRAME_PER_VIDEO: 1200
  BG_CLASS: []

MODEL:
  NAME: 'c2f'

C2F:
  ENSEMBLE_WEIGHTS: [1, 1, 1, 1, 0, 0]

TRAIN:
  BZ: 100
  LR: 0.0001
  NUM_EPOCHS: 300
  WEIGHT_DECAY: 0.0003
  STEP_SIZE: 300
  GAMMA: 0.5
  NUM_WORKER: 3
  LOG_FREQ: 10

