DATA: 
  PATH: "/home/dinggd/datasets"
  DATASET: "breakfast"
  SAMPLE_RATE: 1
  TEMPORAL_AUG: True
  FEATURE_DIM: 2048
  SPLIT: 1

MODEL:
  NAME: 'diffact'

DIFFACT:
  ENCODER_PARAMS:
    USE_INSTANCE_NORM: False
    NUM_LAYERS: 12
    NUM_F_MAPS: 256
    KERNEL_SIZE: 5
    NORMAL_DROPOUT_RATE: 0.5
    CHANNEL_DROPOUT_RATE: 0.1
    TEMPORAL_DROPOUT_RATE: 0.1
    FEATURE_LAYER_INDICES:
    - 7
    - 8
    - 9

  DECODER_PARAMS:
    NUM_LAYERS: 8
    NUM_F_MAPS: 128
    TIME_EMB_DIM: 512
    KERNEL_SIZE: 5
    DROPOUT_RATE: 0.1

  DIFFUSION_PARAMS:
    TIMESTEPS: 1000
    SAMPLING_TIMESTEPS: 25
    DDIM_SAMPLING_ETA: 1.0
    SNR_SCALE: 0.5
    COND_TYPES:
    - "full"
    - "zero"
    - "boundary03-"
    - "segment=1"
    - "segment=1"
    DETACH_DECODER: False

  POSTPROCESS:
    TYPE: "median"
    VALUE: 15


LOSS_WEIGHTS:
  ENCODER_CE_LOSS: 0.5
  ENCODER_MSE_LOSS: 0.025
  ENCODER_BOUNDARY_LOSS: 0.0
  DECODER_CE_LOSS: 0.5
  DECODER_MSE_LOSS: 0.025
  DECODER_BOUNDARY_LOSS: 0.1

TRAIN:
  BZ: 4
  LR: 0.0001
  WEIGHT_DECAY: 0.0
  NUM_EPOCHS: 1001
  LOG_FREQ: 20
  CLASS_WEIGHTING: True
  SET_SAMPLING_SEED: True
  BOUNDARY_SMOOTH: 3
  SOFT_LABEL: 4.0
  LOG_TRAIN_RESULTS: False
