from yacs.config import CfgNode as CN

_C = CN(new_allowed=True)

_C.DATA = CN()
_C.DATA.PATH = "/home/dinggd/datasets"
_C.DATA.DATASET = "breakfast"
_C.DATA.SAMPLE_RATE = 1
_C.DATA.TEMPORAL_AUG = True
_C.DATA.FEATURE_DIM = 2048
_C.DATA.VID_LIST_FILE = ""
_C.DATA.VID_LIST_FILE_TEST = ""
_C.DATA.FEATURES_PATH = ""
_C.DATA.GT_PATH = ""
_C.DATA.MAPPING_FILE = ""
_C.DATA.ACTIONS_DICT = ()
_C.DATA.NUM_CLASSES = 0
_C.DATA.SPLIT = 1


_C.MODEL = CN()
_C.MODEL.NAME = "mstcn"
_C.MODEL.PARAMS = CN(new_allowed=True)

MSTCN = CN()
MSTCN.NUM_STAGES = 4
MSTCN.NUM_LAYERS = 10
MSTCN.NUM_F_MAPS = 64

ASFORMER = CN()
ASFORMER.NUM_STAGES = 4
ASFORMER.NUM_LAYERS = 10
ASFORMER.NUM_F_MAPS = 64
ASFORMER.NUM_DECODERS = 4
ASFORMER.CHANNEL_MASK_RATE = 0.3
ASFORMER.R1 = 2
ASFORMER.R2 = 2

DIFFACT = CN()
DIFFACT.ENCODER_PARAMS = CN()
DIFFACT.ENCODER_PARAMS.USE_INSTANCE_NORM = False
DIFFACT.ENCODER_PARAMS.NUM_LAYERS = 10
DIFFACT.ENCODER_PARAMS.NUM_F_MAPS = 64
DIFFACT.ENCODER_PARAMS.KERNEL_SIZE = 5
DIFFACT.ENCODER_PARAMS.NORMAL_DROPOUT_RATE = 0.5
DIFFACT.ENCODER_PARAMS.CHANNEL_DROPOUT_RATE = 0.5
DIFFACT.ENCODER_PARAMS.TEMPORAL_DROPOUT_RATE = 0.5
DIFFACT.ENCODER_PARAMS.FEATURE_LAYER_INDICES = [5, 7, 9]

DIFFACT.DECODER_PARAMS = CN()
DIFFACT.DECODER_PARAMS.NUM_LAYERS = 8
DIFFACT.DECODER_PARAMS.NUM_F_MAPS = 24
DIFFACT.DECODER_PARAMS.TIME_EMB_DIM = 512
DIFFACT.DECODER_PARAMS.KERNEL_SIZE = 5
DIFFACT.DECODER_PARAMS.DROPOUT_RATE = 0.1

DIFFACT.DIFFUSION_PARAMS = CN()
DIFFACT.DIFFUSION_PARAMS.TIMESTEPS = 1000
DIFFACT.DIFFUSION_PARAMS.SAMPLING_TIMESTEPS = 25
DIFFACT.DIFFUSION_PARAMS.DDIM_SAMPLING_ETA = 1.0
DIFFACT.DIFFUSION_PARAMS.SNR_SCALE = 0.5
DIFFACT.DIFFUSION_PARAMS.COND_TYPES = [
    "full",
    "zero",
    "boundary03-",
    "segment=1",
    "segment=1",
]
DIFFACT.DIFFUSION_PARAMS.DETACH_DECODER = False

DIFFACT.POSTPROCESS = CN()
DIFFACT.POSTPROCESS.TYPE = "purge"
DIFFACT.POSTPROCESS.VALUE = 3


_C.TRAIN = CN(new_allowed=True)
_C.TRAIN.BZ = 6
_C.TRAIN.LR = 0.0005
_C.TRAIN.NUM_EPOCHS = 50
_C.TRAIN.WEIGHT_DECAY = 1e-6
_C.TRAIN.CLASS_WEIGHTING = True
_C.TRAIN.BOUNDARY_SMOOTH = 1
_C.TRAIN.SOFT_LABEL = 1.4
_C.TRAIN.LOG_TRAIN_RESULTS = False
_C.TRAIN.LOG_FREQ = 100
_C.TRAIN.SET_SAMPLING_SEED = True
_C.TRAIN.SEED = 1538574472


_C.TRAIN.LOG_DIR = ""
_C.TRAIN.MODEL_DIR = ""
_C.TRAIN.RESULT_DIR = ""
_C.TRAIN.LOG_FILENAME = ""
_C.TRAIN.RES_FILENAME = ""
_C.TRAIN.CFG_FILENAME = ""
_C.TRAIN.RESUME = False
_C.TRAIN.EVAL = False
_C.TRAIN.DEBUG = False
_C.TRAIN.SETUP = "naive"
_C.TRAIN.EXP_NAME = ""

_C.LOSS_WEIGHTS = CN(new_allowed=True)


def update_config(cfg, args):
    cfg.defrost()
    # read in config first to figure out the model being used
    cfg.merge_from_file(args.cfg)
    # load defaults to back model in case the yaml does not specify the some defaults
    # ensure that cdg.MODEL.PARAMS is referring the same object as cfg.MSTCN, cfg.ASFORMER, etc. so merge_from_file() overrides configuration on both variables
    if cfg.MODEL.NAME == "mstcn":
        cfg.MODEL.PARAMS = cfg.MSTCN = MSTCN
    elif cfg.MODEL.NAME == "asformer":
        cfg.MODEL.PARAMS = cfg.ASFORMER = ASFORMER
    elif cfg.MODEL.NAME == "diffact":
        cfg.MODEL.PARAMS = cfg.DIFFACT = DIFFACT
    # overwrite the existing/default configs with parsed in file and options
    cfg.merge_from_file(args.cfg)
    cfg.merge_from_list(args.opts)
