from yacs.config import CfgNode as CN

_C = CN(new_allowed=True)

_C.DATA = CN()
_C.DATA.PATH = "/home/dinggd/datasets"
_C.DATA.DATASET = "breakfast"
_C.DATA.SAMPLE_RATE = 1
_C.DATA.FEATURE_DIM = 2048
_C.DATA.VID_LIST_FILE = ""
_C.DATA.VID_LIST_FILE_TEST = ""
_C.DATA.FEATURES_PATH = ""
_C.DATA.GT_PATH = ""
_C.DATA.MAPPING_FILE = ""
_C.DATA.ACTIONS_DICT = ()
_C.DATA.NUM_CLASSES = 0
_C.DATA.SPLIT = 1


_C.MODEL = CN()
_C.MODEL.NAME = "mstcn"
_C.MODEL.PARAMS = CN(new_allowed=True)

MSTCN = CN()
MSTCN.NUM_STAGES = 4
MSTCN.NUM_LAYERS = 10
MSTCN.NUM_F_MAPS = 64

ASFORMER = CN()
ASFORMER.NUM_STAGES = 4
ASFORMER.NUM_LAYERS = 10
ASFORMER.NUM_F_MAPS = 64
ASFORMER.NUM_DECODERS = 4
ASFORMER.CHANNEL_MASK_RATE = 0.3
ASFORMER.R1 = 2
ASFORMER.R2 = 2


DIFFUSION = CN()
DIFFUSION.ENCODER_PARAMS = CN()
DIFFUSION.ENCODER_PARAMS.USE_INSTANCE_NORM = False
DIFFUSION.ENCODER_PARAMS.NUM_LAYERS = 10
DIFFUSION.ENCODER_PARAMS.NUM_F_MAPS = 64
DIFFUSION.ENCODER_PARAMS.KERNEL_SIZE = 5
DIFFUSION.ENCODER_PARAMS.NORMAL_DROPOUT_RATE = 0.5
DIFFUSION.ENCODER_PARAMS.CHANNEL_DROPOUT_RATE = 0.5
DIFFUSION.ENCODER_PARAMS.TEMPORAL_DROPOUT_RATE = 0.5
DIFFUSION.ENCODER_PARAMS.FEATURE_LAYER_INDICES = [5, 7, 9]

DIFFUSION.DECODER_PARAMS = CN()
DIFFUSION.DECODER_PARAMS.NUM_LAYERS = 8
DIFFUSION.DECODER_PARAMS.NUM_F_MAPS = 24
DIFFUSION.DECODER_PARAMS.TIME_EMD_DIM = 512
DIFFUSION.DECODER_PARAMS.KERNEL_SIZE = 5
DIFFUSION.DECODER_PARAMS.DROP_RATE = 0.1
DIFFUSION.DECODER_PARAMS.INPUT_DIM = []

DIFFUSION.DIFFUSION_PARAMS = CN()
DIFFUSION.DIFFUSION_PARAMS.TIMESTEPS = 1000
DIFFUSION.DIFFUSION_PARAMS.SAMPLING_TIMESTEPS = 25
DIFFUSION.DIFFUSION_PARAMS.DDIM_SAMPLING_ETA = 1.0
DIFFUSION.DIFFUSION_PARAMS.SNR_SCALE = 0.5
DIFFUSION.DIFFUSION_PARAMS.COND_TYPES = [
    "full",
    "zero",
    "boundary03-",
    "segment=1",
    "segment=1",
]
DIFFUSION.DIFFUSION_PARAMS.DETACH_DECODER = False


DIFFUSION.POSTPROCESS = CN()
DIFFUSION.POSTPROCESS.TYPE = "purge"
DIFFUSION.POSTPROCESS.VALUE = 3


_C.TRAIN = CN(new_allowed=True)
_C.TRAIN.BZ = 6
_C.TRAIN.LR = 0.0005
_C.TRAIN.NUM_EPOCHS = 50
_C.TRAIN.WEIGHT_DECAY = 1e-6
_C.TRAIN.CLASS_WEIGHTING = True
_C.TRAIN.BOUNDARY_SMOOTH = 1
_C.TRAIN.SOFT_LABEL = 1.4
_C.TRAIN.LOG_TRAIN_RESULTS = False
_C.TRAIN.LOG_FREQ = 100
_C.TRAIN.SET_SAMPLING_SEED = True
_C.TRAIN.SEED = 1538574472


_C.TRAIN.LOG_DIR = ""
_C.TRAIN.MODEL_DIR = ""
_C.TRAIN.RESULT_DIR = ""
_C.TRAIN.LOG_FILENAME = ""
_C.TRAIN.RES_FILENAME = ""
_C.TRAIN.CFG_FILENAME = ""
_C.TRAIN.RESUME = False
_C.TRAIN.EVAL = False
_C.TRAIN.DEBUG = False
_C.TRAIN.SETUP = "naive"
_C.TRAIN.EXP_NAME = ""


def update_config(cfg, args):
    cfg.defrost()
    # read in config first to figure out the model being used
    cfg.merge_from_file(args.cfg)
    # load defaults to back model in case the yaml does not specify the some defaults
    if cfg.MODEL.NAME == "mstcn":
        cfg.MODEL.PARAMS = MSTCN
    elif cfg.MODEL.NAME == "asformer":
        cfg.MODEL.PARAMS = ASFORMER
    elif cfg.MODEL.NAME == "diffusion":
        cfg.MODEL.PARAMS = DIFFUSION
    # overwrite the existing/default configs with parsed in file and options
    cfg.merge_from_file(args.cfg)
    cfg.merge_from_list(args.opts)
